title: "DMP's Website"
email: "dangminhphuc505@gmail.com"
description: >-
  Đây là website cá nhân của tôi, nơi chia sẻ kiến thức và kinh nghiệm của bản thân.

# ⚠️ QUAN TRỌNG: Kiểm tra `baseurl` và `url`
baseurl: "/my-web"  # Nếu repo KHÔNG phải <username>.github.io thì cần baseurl
url: "https://tis51t.github.io"  # Đúng với domain của GitHub Pages

github_username: tis51T

# ✅ Thêm plugin để đảm bảo theme Minima hoạt động
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # Thêm plugin SEO giúp tránh lỗi

# ✅ Cấu hình Minima
minima:
  skin: classic
  date_format: "%b %-d, %Y"

# ✅ Hỗ trợ Markdown + MathJax (Latex)
markdown: kramdown
kramdown:
  math_engine: mathjax
